## mysql配置
user = "root"
password = "tJipDi4shJaj"
host = "10.33.12.241"
port = 3306
database = "cron_v2"
charset = "utf8"

## log表日至最长保留天数，默认保留30天的日志数据
log_keep_day = 1

## redis 配置
redis_address = "10.33.5.186:6379"
redis_password = "HRBB2lwy2gASbWqR"
leader_key = "xllive/wing-crontab/leader"
redis_key_prex = "xllive/wing-crontab/task"