## mysql配置
user = "root"
password = "tJipDi4shJaj"
host = "10.33.12.241"
port = 3306
database = "cron_v2"
charset = "utf8"

## log表日至最长保留天数，默认保留30天的日志数据
log_keep_day = 1

## redis 配置
redis_address = "127.0.0.1:6379"
redis_password = ""
leader_key = "xllive/xcrontab/leader"
redis_key_prex = "xllive/xcrontab/task"