consul_address = "127.0.0.1:8500"
##service name
service_name = "wing-crontab-service"
##use for select leader
##all service nodes should be same
lock_key = "wing-crontab-lock"
##tcp service listen address
##do not use "0.0.0.0:9991", must be ip:port
bind_address = "127.0.0.1:9991"
http_bind_address = "127.0.0.1:9990"
pprof_listen = "127.0.0.1:8880"
log_level=5

mysql_user = "root"
mysql_password = "123456"
mysql_host = "127.0.0.1"
mysql_port = 3306
mysql_database = "cron"
mysql_charset = "utf8"